### ISSUE TITLE
Expose stored data with REST API

### ISSUE THREAD

**Issue by studro** [justinkhart/OverwatchChumps#13]
A REST API could be added to expose stored data.

This would enable other applications (i.e. pubg.thatscloud.org - now currently only used for PUBG) - to display Overwatch data.

It would also be handy if the REST API could enable the addition of players to track (with auth headers, of course).

**Comment by justinkhart** [comment]
Closing this as it was kind of fixed. Adding the rest of it over on the other project, see below. 

[https://github.com/justinkhart/Function-OverwatchAPI](url)
