### ISSUE TITLE
Add setup guide for testing local server in README.md or wiki entry

### ISSUE THREAD

**Issue by studro** [justinkhart/OverwatchChumps#5]
This might seem like a stupid question for C# developers, but is it possible to create an README.md file or wiki entry, containing a short series of steps (perhaps with screenshots) on how to get a server up and running locally?

Ideally, I'd like to test any changes I make before submitting a pull request for review.

**Comment by justinkhart** [comment]
You are right, most of it is built in, but I'd be happy to write up something real quick tonight.

**Comment by studro** [comment]
Yeah, this looks good.
